schema_version = "1.0.0"

id = "openvat"
version = "1.1.0"
name = "OpenVAT"
tagline = "Encode and preview vertex animation textures"
maintainer = "Luke Stilson <stilson.luke@gmail.com>"
type = "add-on"
blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
